# Continuous integration procedure for AppVeyor
# Based on https://raw.githubusercontent.com/choderalab/itctools/master/appveyor.yml

version: 1.0.{build}
image: macOS

environment:
  matrix:
    - python: 3.5
    - python: 3.6

install:
  - echo "source ${HOME}/venv${python}/bin/activate"
  - sh: source ${HOME}/venv${python}/bin/activate
  - sh: python3 -m pip install --upgrade pip  
  - sh: python3 pip install -r requirements.txt
  - sh: python3 pip install -e .
  - cmd: parserator train training/labeled.xml usaddress
 
build: false
 
test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests --with-coverage --cover-package=usaddress

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  - coverage report
