# Continuous integration procedure for AppVeyor
# Based on https://raw.githubusercontent.com/choderalab/itctools/master/appveyor.yml

version: 1.0.{build}
image: Visual Studio 2019 Preview

environment:
  matrix:
    - python: 27-x64
    - python: 35-x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
  - python -m pip install --upgrade pip  
  - pip install -r requirements.txt
  - pip install -e .
 
build: false
  verbosity: minimal
  
test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests --with-coverage --cover-package=usaddress

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  - coverage report
  - parserator train training/labeled.xml usaddress
